template:
  - sensor:
      - name: Security monitoring
        unique_id: security_monitoring
        state: >
          {%- if states('input_select.scene') in ['Away (Day)', 'Away (Night)', 'Sleep', 'unknown', 'unavailable'] -%}
            {%- if 'Away' in states('input_select.scene') and states('input_boolean.pets_home_alone') == 'off' -%}
              all sensors
            {%- else -%}
              outdoor sensors
            {%- endif -%}
          {%- else -%}
            off
          {%- endif -%}
        icon: mdi:cctv
        attributes:
          count_text: >
            {%- set person_count = states('sensor.person_detected_count')|int(0) -%}
            {%- set motion_count = states('sensor.motion_detected_count')|int(0) -%}
            {%- if person_count + motion_count == 0 -%}
              No motion detected
            {%- else -%}
              {%- set security_type = "Person" if person_count > 0 else "Motion" -%}
              {%- set count = person_count if person_count > 0 else motion_count -%}
              {{ security_type }} detected {{ count }} time{{ 's' if count > 1 else '' }}
            {%- endif -%}
      - name: Person detected count
        unique_id: person_detected_count
        state: >
          {{
            states('sensor.person_detected_count_front_door')|int(0) +
            states('sensor.person_detected_count_garage')|int(0) +
            states('sensor.person_detected_count_back_door')|int(0) +
            states('sensor.person_detected_count_back_deck')|int(0) + 
            states('sensor.person_detected_count_front_door_doorbell')|int(0) + (
            (
              states('sensor.person_detected_count_entryway')|int(0) +
              states('sensor.person_detected_count_living_room')|int(0) +
              states('sensor.person_detected_count_kitchen_door')|int(0) +
              states('sensor.person_detected_count_dining_room_balcony_door')|int(0) +
              states('sensor.person_detected_count_bedroom_balcony_door')|int(0) +
              states('sensor.person_detected_count_nursery_door')|int(0)
            ) if states('sensor.security_monitoring') == "all sensors" else 0)
          }}
        icon: mdi:motion-sensor
      - name: Motion detected count
        unique_id: motion_detected_count
        state: >
          {{
            states('sensor.motion_detected_count_front_door')|int(0) +
            states('sensor.motion_detected_count_garage')|int(0) +
            states('sensor.motion_detected_count_back_door')|int(0) +
            states('sensor.motion_detected_count_back_deck')|int(0) +
            states('sensor.motion_detected_count_front_door_doorbell')|int(0) + (
            (
              states('sensor.motion_detected_count_entryway')|int(0) +
              states('sensor.motion_detected_count_living_room_camera')|int(0) +
              states('sensor.motion_detected_count_kitchen')|int(0) +
              states('sensor.motion_detected_count_living_room')|int(0) +
              states('sensor.motion_detected_count_bedroom')|int(0) +
              states('sensor.motion_detected_count_nursery')|int(0) +
              states('sensor.motion_detected_count_office')|int(0) +
              states('sensor.motion_detected_count_entryway_multisensor')|int(0) +
              states('sensor.motion_detected_count_dining_room_multisensor')|int(0) +
              states('sensor.motion_detected_count_hall_multisensor')|int(0) +
              states('sensor.motion_detected_count_bathroom_multisensor')|int(0)
            ) if states('sensor.security_monitoring') == "all sensors" else 0)
          }}
        icon: mdi:motion-sensor
  - triggers:
      - trigger: state
        entity_id: sensor.security_monitoring
        from: "off"
        not_to:
          - "unknown"
          - "unavaiable"
    sensor:
      - name: Security monitoring start time
        unique_id: security_monitoring_start_time
        state: "{{ now() }}"
        device_class: timestamp

sensor:
  - platform: history_stats
    name: Person detected count front door
    unique_id: person_detected_count_front_door
    entity_id: binary_sensor.front_door_person_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count entryway
    unique_id: person_detected_count_entryway
    entity_id: binary_sensor.entryway_person_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count living room
    unique_id: person_detected_count_living_room
    entity_id: binary_sensor.living_room_person_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count garage
    unique_id: person_detected_count_garage
    entity_id: binary_sensor.garage_person_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count back deck
    unique_id: person_detected_count_back_deck
    entity_id: binary_sensor.back_deck_person_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count back door
    unique_id: person_detected_count_back_door
    entity_id: binary_sensor.back_door_person_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Person detected count front door doorbell
    unique_id: person_detected_count_front_door_doorbell
    entity_id: binary_sensor.doorbell_ringing
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count kitchen door
    unique_id: person_detected_count_kitchen_door
    entity_id: binary_sensor.kitchen_door_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count dining room balcony door
    unique_id: person_detected_count_dining_room_balcony_door
    entity_id: binary_sensor.dining_room_balcony_door_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count bedroom balcony door
    unique_id: person_detected_count_bedroom_balcony_door
    entity_id: binary_sensor.bedroom_balcony_door_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Person detected count nursery door
    unique_id: person_detected_count_nursery_door
    entity_id: binary_sensor.nursery_door_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Motion detected count front door
    unique_id: motion_detected_count_front_door
    entity_id: binary_sensor.front_door_motion_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count entryway
    unique_id: motion_detected_count_entryway
    entity_id: binary_sensor.entryway_motion_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count living room camera
    unique_id: motion_detected_count_living_room_camera
    entity_id: binary_sensor.living_room_motion_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count garage
    unique_id: motion_detected_count_garage
    entity_id: binary_sensor.garage_motion_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count back deck
    unique_id: motion_detected_count_back_deck
    entity_id: binary_sensor.back_deck_motion_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count back door
    unique_id: motion_detected_count_back_door
    entity_id: binary_sensor.back_door_motion_detected
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"

  # TODO: reduce mmWave sensor sensitivity or replace with bayesian sensors
  - platform: history_stats
    name: Motion detected count kitchen
    unique_id: motion_detected_count_kitchen
    entity_id: binary_sensor.kitchen_presence_sensor_occupancy
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count living room
    unique_id: motion_detected_count_living_room
    entity_id: binary_sensor.living_room_presence_sensor_occupancy
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count bedroom
    unique_id: motion_detected_count_bedroom
    entity_id: binary_sensor.bedroom_presence_sensor_occupancy
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count nursery
    unique_id: motion_detected_count_nursery
    entity_id: binary_sensor.nursery_presence_sensor_occupancy
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count office
    unique_id: motion_detected_count_office
    entity_id: binary_sensor.office_presence_sensor_occupancy
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Motion detected count entryway multisensor
    unique_id: motion_detected_count_entryway_multisensor
    entity_id: binary_sensor.entryway_multisensor_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count dining room multisensor
    unique_id: motion_detected_count_dining_room_multisensor
    entity_id: binary_sensor.dining_room_multisensor_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count hall multisensor
    unique_id: motion_detected_count_hall_multisensor
    entity_id: binary_sensor.hall_multisensor_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Motion detected count bathroom multisensor
    unique_id: motion_detected_count_bathroom_multisensor
    entity_id: binary_sensor.bathroom_multisensor_motion
    state: "on"
    type: count
    start: "{{ states('sensor.security_monitoring_start_time') if has_value('sensor.security_monitoring_start_time') else now() }}"
    end: "{{ now() }}"
